spring.datasource.url=jdbc:mysql://193.203.175.134:3306/u969339482_CANTALLOC
spring.datasource.username=u969339482_dev
spring.datasource.password=2Cw[>W@PaG
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

logging.level.root=debug

server.port=8082

spring.main.allow-bean-definition-overriding=true